language: d

os:
    - linux
    - osx

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  - dmd-2.071.2
  - dmd-2.070.2
  - ldc-1.0.0
  - dmd-beta

env:
    - CONFIG=select
    - CONFIG=epoll
    - CONFIG=libasync

matrix:
  allow_failures:
    - env: CONFIG=libasync

script: ./travis-ci.sh

sudo: false
